# Generated by Django 3.1.2 on 2020-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20201008_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknumber',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
