# Generated by Django 3.1.2 on 2020-10-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20201008_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='demo.Book'),
        ),
    ]
